CC = gcc
CFLAGS = -Wall -Wextra -Werror
AR = ar crv
RM = rm -f
NAME = libft.a
SRCS = ft_memset.c ft_bzero.c ft_memcpy.c ft_memccpy.c ft_memmove.c ft_memchr.c ft_memcmp.c ft_strlen.c ft_strlcpy.c ft_strlcat.c ft_strchr.c ft_strrchr.c ft_strnstr.c ft_strncmp.c ft_atoi.c ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c ft_toupper.c ft_tolower.c ft_calloc.c ft_strdup.c ft_substr.c ft_strjoin.c ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c
BSRC = ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstlast.c ft_lstadd_back.c ft_lstdelone.c ft_lstclear.c ft_lstiter.c ft_lstmap.c
OBJS = $(SRCS:.c=.o)
BOBJ = $(BSRC:.c=.o)
INC = libft.h

all : $(NAME)

%.o: %.c $(INC)
	@printf "\033[0;33mGenerating libft objects... %-33.33s\r" $@
	@$(CC) $(CFLAGS) -c $< -o $(<:.c=.o) -I $(INC)

$(NAME) : $(OBJS)
	@echo "\n\n\033[0;32mCompiling libft..."
	@ar rc $(NAME) $^
	@ranlib $(NAME)
	@echo "\033[0m"

bonus : $(NAME) $(BOBJ)
	@$(AR) $(NAME) $(BOBJ)
	@ranlib $(NAME)

clean :
	@$(RM) $(OBJS) $(BOBJ)

fclean : clean
	@$(RM) $(NAME)

re : fclean all
